### PR TITLE
[wip] item: Workaround possible gimp crash

### LINKED ISSUE #31: qlipper is able (probably) to crash gimp
https://github.com/lxde/lxqt/issues/858

### PR DESCRIPTION
**Pull request by palinek**
I'm still not convinced that qlipper should do workarounds, but this will help and will not harm much anyone else.

fixes #31

### CODE REVIEW

**Comment by palinek** [comment]
ping

**Comment by palinek** [comment]
ping 2

**Comment by palinek** [comment]
@pvanek is there a reason for not touching this?

**Comment by pvanek** [comment]
just workload in my regular job :/

**Pull request merged**
