### PR TITLE
set Qt::AA_UseHighDpiPixmaps to true

### PR DESCRIPTION
**Pull request by agaida**
while i'm on it

### CODE REVIEW

**Comment by palinek** [comment]
Actually... looking on all those PRs... I would suggest to make this configurable. So configuration option in `lxqt-config-appearance` and setting/unsetting it in `lxqt-qtplugin`. With that we:
- will not brute force the extended memory usage for poor hardware (if used doesn't want it)
- will have the setting/unsetting centralized
- will set/unset it for all Qt apps, not just our

What do you think?
@agaida @PCMan @luis-pereira @tsujan

**Comment by agaida** [comment]
i would suggest to test it and see what this change does regarding ressources. And if we can override these values if needed via lxqt-config and lxqt-qtplugin i'm all for it. If i understand the Pixmaps thing right it should not do much harm with normal monitors, only some kind of magic with High DPI devices that are detected by Qt.

**Comment by tsujan** [comment]
> will not brute force the extended memory usage for poor hardware

Setting `Qt::AA_UseHighDpiPixmaps` to `true` causes no tangible extra memory or CPU usage.

> will have the setting/unsetting centralized

How can `Qt::AA_UseHighDpiPixmaps` be unset when it's in the app code? I think there's a misunderstanding here.

**Comment by agaida** [comment]
@tsujan - i never tested it - but it is worth a try - and to be true, that will be not needed if no or not much extra ressources are needed for that - and so i read the documentation too.

**Comment by tsujan** [comment]
> @tsujan - i never tested it - but it is worth a try - and to be true, that will be not needed if no or not much extra ressources are needed for that - and so i read the documentation too.

I really don't get what you and @palinek are talking about! Which extra resources? Which setting/unsetting?

**Comment by tsujan** [comment]
This is just about choosing the correct icon size when QT_SCALE_FACTOR is greater than 1. For example, if it's 2, 32px icons are used where the icon size should be 16px.

**Comment by palinek** [comment]
> I really don't get what you and @palinek are talking about! Which extra resources?

The doc:
`Make QIcon::pixmap() generate high-dpi pixmaps that can be larger than the requested size. Such pixmaps will have devicePixelRatio() set to a value higher than 1. After setting this attribute, application code that uses pixmap sizes in layout geometry calculations should typically divide by devicePixelRatio() to get device-independent layout geometry.`

`Setting the Qt::AA_UseHighDpiPixmaps application attribute enables this function to return pixmaps that are larger than the requested size. Such images will have a devicePixelRatio larger than 1.`

... I believe that larger pixmap has bigger memory footprint, so the bigger resources usage is obvious, not?

**Comment by tsujan** [comment]
@palinek That just means, with a factor of 2,  32px instead of 16px, 96 instead of 48.... I did it in Kvantum years ago so that even if `Qt::AA_UseHighDpiPixmaps` is false, the same thing will happen with factors greater than 1. If someone uses an HDPI monitor, he can't have a computer from the 20th century and those that don't have hdpi, will see no difference at all -- neither in icons nor in their RAM?CPU usage. Actually, those *with* hdpi screens see no difference either until they set that factor to ≥ 2.

**Pull request closed without merging**
